# Generated by Django 4.2.7 on 2025-09-18 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('digital_gift', 'デジタルギフト'), ('corporate_product', '企業商品')], max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('ratio', models.DecimalField(decimal_places=2, help_text='0.60 = 60%', max_digits=3, verbose_name='比率')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'ポイントカテゴリ',
                'verbose_name_plural': 'ポイントカテゴリ',
                'db_table': 'point_categories',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='付与ポイント数')),
                ('remaining_amount', models.PositiveIntegerField(verbose_name='残りポイント数')),
                ('reason', models.CharField(max_length=200, verbose_name='付与理由')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='付与日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('is_expired', models.BooleanField(default=False, verbose_name='期限切れ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pointcategory', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ポイント',
                'verbose_name_plural': 'ポイント',
                'db_table': 'points',
                'ordering': ['expires_at'],
                'indexes': [models.Index(fields=['user', 'category', 'expires_at'], name='points_user_id_cda03d_idx'), models.Index(fields=['expires_at', 'is_expired'], name='points_expires_e803be_idx')],
            },
        ),
    ]
