version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=incentive_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d incentive_system"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-local-development-key-change-in-production
      - USE_POSTGRESQL=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=incentive_system
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - USE_REDIS=True
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,web,0.0.0.0
      - COMPANY_NAME=ABC商事株式会社
      - SYSTEM_NAME=営業成果インセンティブシステム
      - SYSTEM_SHORT_NAME=ABC インセンティブ
      - COMPANY_COLOR_PRIMARY=#2c5282
      - COMPANY_COLOR_SECONDARY=#4a5568
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
