# Generated by Django 4.2.7 on 2025-09-18 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('grant', 'ポイント付与'), ('exchange', '商品交換'), ('expire', 'ポイント失効'), ('adjustment', '調整')], max_length=20, verbose_name='取引種別')),
                ('amount', models.IntegerField(verbose_name='ポイント数')),
                ('balance_after', models.PositiveIntegerField(verbose_name='取引後残高')),
                ('reason', models.CharField(max_length=200, verbose_name='理由・説明')),
                ('related_point_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='関連ポイントID')),
                ('related_product_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='関連商品ID')),
                ('related_exchange_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='関連交換ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pointcategory', verbose_name='カテゴリ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ポイント取引履歴',
                'verbose_name_plural': 'ポイント取引履歴',
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='point_trans_user_id_7622fc_idx'), models.Index(fields=['transaction_type', 'created_at'], name='point_trans_transac_a938a0_idx'), models.Index(fields=['category', 'created_at'], name='point_trans_categor_63dc77_idx')],
            },
        ),
    ]
