# Generated by Django 4.2.7 on 2025-09-18 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('description', models.TextField(blank=True, verbose_name='商品説明')),
                ('required_points', models.PositiveIntegerField(verbose_name='必要ポイント数')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品画像')),
                ('is_active', models.BooleanField(default=True, verbose_name='販売中')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.pointcategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField(verbose_name='使用ポイント数')),
                ('exchange_date', models.DateTimeField(auto_now_add=True, verbose_name='交換日時')),
                ('status', models.CharField(choices=[('pending', '交換申請中'), ('processing', '処理中'), ('completed', '交換完了'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='状態')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '商品交換履歴',
                'verbose_name_plural': '商品交換履歴',
                'db_table': 'product_exchanges',
                'ordering': ['-exchange_date'],
            },
        ),
    ]
